# -*- coding: utf-8 -*-
"""SuperF SR Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1Ub47ywT1k_61N1DqH5NYoRBJLQTbdm

# SuperF Demo
This script demonstrates how to use direct COG (Cloud Optimized GeoTIFF) access
to efficiently sample small areas from Sentinel-2 imagery without downloading
entire tiles.

The approach:
1. Use pystac-client to search for Sentinel-2 COGs
2. Get direct URLs to COG files
3. Use rasterio to read only the specific window needed
4. Save as PNG files
"""

from pathlib import Path
from datetime import datetime, timedelta
import rasterio
from rasterio.windows import Window
from rasterio.warp import transform as transform_coords
from PIL import Image
from pystac_client import Client

import numpy as np
import torch

from omnicloudmask import predict_from_array

# Enter the coordinates for the point you want to find (You can directly use the Google Maps coordinates when rightclicking a point)
#LAT, LON = -33.93954978647778, 18.460735667396914
#LAT, LON = 25.00761536263627, -77.49812237909057  # CPH DIKU
#LAT, LON = 25.261389, 9.508889  # Key hole 1
#LAT, LON = 25.263056,  7.813889  # Key hole 2
#LAT, LON =  55.638016,  12.578422 # Bella Centre Copenhagen. #25 images
LAT, LON  =  19.434495,  -99.146264 # Hilton Mexico City Reforma. #10 images
#LAT, LON  =  32.705752, -117.160507 # San Diego Convention Center. #23
LAT, LON = 58.72132425373909, 9.229434602964929


SIZE_PIXELS = 100   # Size of area in pixels (100x100)
SIZE_DEGREES = SIZE_PIXELS * 0.0001 # 0.01 # Size in degrees (about 1km x 1km)

# Then choose the start and end date for when to search for images in the STAC
START_DATE = "2025-04-01"
END_DATE = "2025-06-30"

# Set the maximum percentage of snow allowed
SNOW_MAX_PERCENT = 0
CLOUD_MAX_PERCENT = 0

# STAC endpoint and use L2A products from Sentinel 2
STAC_ENDPOINT = "https://earth-search.aws.element84.com/v1"
COLLECTION = "sentinel-2-l2a"

import shutil

def create_output_directory(base_dir="output_cog"):
    """Delete and recreate output directory structure"""
    output_dir = Path(base_dir)

    # Remove the directory if it already exists
    if output_dir.exists() and output_dir.is_dir():
        shutil.rmtree(output_dir)

    # Create the fresh output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir

def get_search_bounds(center_lat, center_lon, size_degrees):
    """Get bounding box for area of interest"""
    half_size = size_degrees / 2
    return [
        center_lon - half_size,  # west
        center_lat - half_size,  # south
        center_lon + half_size,  # east
        center_lat + half_size   # north
    ]

def search_sentinel2_cogs(bbox):
    catalog = Client.open(STAC_ENDPOINT)
    search = catalog.search(
        collections=[COLLECTION],
        bbox=bbox,
        datetime=f"{START_DATE}/{END_DATE}"
    )

    items = list(search.get_items())

    print(f"Found {len(items)} items in the STAC catalog between {START_DATE} - {END_DATE}")

    return items

def get_cloud_cover(data):
    x = data[:3].astype(np.float32)
    if x.max() > 1.5:
        x = np.clip(x / 255.0, 0.0, 1.0)
    input_array = x

    pred_mask = predict_from_array(input_array)
    cloud_percentage = (np.sum(pred_mask > 0) / pred_mask.size) * 100
    return cloud_percentage

def save_as_png(data, output_path):
  # Transpose from (channels, height, width) to (height, width, channels)
  data = np.transpose(data, (1, 2, 0))
  
  # Convert to uint8 if needed (visual asset should already be uint8)
  if data.dtype != np.uint8:
    data = data.astype(np.uint8)
  
  # Ensure values are in valid range
  data = np.clip(data, 0, 255).astype(np.uint8)

  # Create PIL Image and save as PNG
  image = Image.fromarray(data)
  image.save(output_path, 'PNG')

def read_cog_window(cog_url, lat, lon, window_size=100, bands=None):
    with rasterio.open(cog_url) as src:
        src_crs = src.crs
        dst_crs = 'EPSG:4326'

        x, y = transform_coords(
            dst_crs, src_crs, [lon], [lat]
        )

        row, col = rasterio.transform.rowcol(src.transform, x[0], y[0])

        # Calculate window bounds around the center point
        half_size = window_size // 2
        row_start = max(0, row - half_size)
        row_end = min(src.height, row + half_size)
        col_start = max(0, col - half_size)
        col_end = min(src.width, col + half_size)

        window = Window(col_start, row_start, col_end - col_start, row_end - row_start)

        data = src.read(bands, window=window)

        transform = rasterio.windows.transform(window, src.transform)

        return data, transform, src_crs

def get_cog_urls(item, bands=['B04', 'B03', 'B02', 'B08']):

    cog_urls = {}

    band_mappings = {
        'B04': ['B04', 'red', 'red-band', 'visual-red'],
        'B03': ['B03', 'green', 'green-band', 'visual-green'],
        'B02': ['B02', 'blue', 'blue-band', 'visual-blue'],
        'B08': ['B08', 'nir', 'nir-band', 'visual-nir']
    }

    for target_band, possible_names in band_mappings.items():
        found = False
        for name in possible_names:
            if name in item.assets:
                asset = item.assets[name]
                if hasattr(asset, 'href') and asset.href:
                    cog_urls[target_band] = asset.href
                    found = True
                    break

        if not found:
            print(f"Warning: Could not find band {target_band} (tried: {possible_names})")

    return cog_urls

def process_scene(scene, bbox, output_dir):
    scene_date = scene.properties.get('datetime', '').split("T")[0]
    scene_id = scene.id

    scl_asset = scene.assets.get("scl") # or scene.assets.get('scl') or scene.assets.get('classification')
    # Ensure scl_asset is not None before proceeding with snow check
    if scl_asset is None:
        print(f"  ✗ No SCL asset found for {scene_id}")
        return {
            "period": scene_id,
            "status": "error",
            "error": "No SCL asset found"
        }

    scl_url = scl_asset.href
    scl_data_tuple = read_cog_window(scl_url, LAT, LON, SIZE_PIXELS)
    scl_data, _, _ = scl_data_tuple
    snw_pct = float(np.sum(scl_data == 11)) / float(scl_data.size) * 100.0

    if snw_pct > SNOW_MAX_PERCENT:
        return {
            "period": scene_id,
            "results": [
                {"type": "SCL", "status": "skipped", "reason": f"snow {snw_pct:.1f}% > {SNOW_MAX_PERCENT:.1f}%"}
            ],
            "status": "skipped_snow"
        }

    tci_dir = output_dir / "TCI"

    tci_dir.mkdir(exist_ok=True)

    if 'visual' in scene.assets:
        visual_url = scene.assets['visual'].href
    else:
        print(f"  ✗ No visual asset found for {scene_id}")
        return {
            "period": scene_id,
            "output_path": None,
            "status": "error",
            "error": "No visual asset found"
        }


    # Get the R, G, NIR data for cloud detection
    assets = scene.assets
    def _href(keys):
        for key in keys:
            if key in assets:
                return assets[key].href
        return None

    r_url = _href(['B04', 'red'])
    g_url = _href(['B03', 'green'])
    n_url = _href(['B08', 'nir'])

    # Ensure all required bands for cloud detection are found
    if not all([r_url, g_url, n_url]):
        print(f"  ✗ Missing required bands for cloud detection for {scene_id}")
        return {
            "period": scene_id,
            "status": "error",
            "error": "Missing required bands for cloud detection"
        }

    r_t = read_cog_window(r_url, LAT, LON, SIZE_PIXELS)
    g_t = read_cog_window(g_url, LAT, LON, SIZE_PIXELS)
    n_t = read_cog_window(n_url, LAT, LON, SIZE_PIXELS)

    r = r_t[0]
    g = g_t[0]
    n = n_t[0]

    r = r[0] if r.ndim == 3 and r.shape[0] == 1 else r
    g = g[0] if g.ndim == 3 and g.shape[0] == 1 else g
    n = n[0] if n.ndim == 3 and n.shape[0] == 1 else n
    r = np.clip(r.astype(np.float32) / 10000.0, 0.0, 1.0)
    g = np.clip(g.astype(np.float32) / 10000.0, 0.0, 1.0)
    n = np.clip(n.astype(np.float32) / 10000.0, 0.0, 1.0)
    input_array = np.stack([r, g, n], axis=0)

    cloud_cover = get_cloud_cover(input_array)
    if cloud_cover > CLOUD_MAX_PERCENT:
        return {
            "period": scene_id,
            "results": [
                {"type": "Cloud", "status": "skipped", "reason": f"cloud {cloud_cover:.1f}% > {CLOUD_MAX_PERCENT:.1f}%"}
            ],
            "status": "skipped_cloud"
        }

    # Read TCI data from COG
    visual_data, _, _ = read_cog_window(visual_url, LAT, LON, SIZE_PIXELS)

    tci_output_path = tci_dir / f"{scene_date}_{scene_id}.png"
    save_as_png(visual_data, tci_output_path)

    return {
        "period": scene_id,
        "output_path": str(tci_output_path),
        "status": "processed"
    }

output_dir = create_output_directory("results")

search_bounds = get_search_bounds(LAT, LON, SIZE_DEGREES)

available_items = search_sentinel2_cogs(search_bounds)

assert len(available_items) > 0, "No items found - please revise the bbox and timeframe"

results = []

for item in available_items:
    result = process_scene(item, search_bounds, output_dir)
    results.append(result)

print("Finished downloading all of the LR samples of the location")

# Summarize the results
print("\n--- Processing Summary ---")
processed_count = 0
skipped_snow_count = 0
skipped_cloud_count = 0
errors_count = 0

for res in results:
    if res["status"] == "skipped_snow":
        skipped_snow_count += 1
        print(f"- Skipped {res['period']} due to snow: {res['results'][0]['reason']}")
    elif res["status"] == "skipped_cloud":
        skipped_cloud_count += 1
        print(f"- Skipped {res['period']} due to clouds: {res['results'][0]['reason']}")
    elif res["status"] == "error":
        errors_count += 1
        print(f"- Error processing {res['period']}: {res['error']}")
    else:
        processed_count += 1
        print(f"- Successfully processed {res['period']}")

print(f"\nTotal items found: {len(available_items)}")
print(f"Successfully processed: {processed_count}")
print(f"Skipped due to snow: {skipped_snow_count}")
print(f"Skipped due to clouds: {skipped_cloud_count}")
print(f"Errors: {errors_count}")

output_dir = create_output_directory("results")

search_bounds = get_search_bounds(LAT, LON, SIZE_DEGREES)

available_items = search_sentinel2_cogs(search_bounds)

assert len(available_items) > 0, "No items found - please revise the bbox and timeframe"

results = []

for item in available_items:
    result = process_scene(item, search_bounds, output_dir)
    results.append(result)

print("Finished downloading all of the LR samples of the location")

# Summarize the results
print("\n--- Processing Summary ---")
processed_count = 0
skipped_snow_count = 0
skipped_cloud_count = 0
errors_count = 0

for res in results:
    if res["status"] == "skipped_snow":
        skipped_snow_count += 1
        print(f"- Skipped {res['period']} due to snow: {res['results'][0]['reason']}")
    elif res["status"] == "skipped_cloud":
        skipped_cloud_count += 1
        print(f"- Skipped {res['period']} due to clouds: {res['results'][0]['reason']}")
    elif res["status"] == "error":
        errors_count += 1
        print(f"- Error processing {res['period']}: {res['error']}")
    else:
        processed_count += 1
        print(f"- Successfully processed {res['period']}")

print(f"\nTotal items found: {len(available_items)}")
print(f"Successfully processed: {processed_count}")
print(f"Skipped due to snow: {skipped_snow_count}")
print(f"Skipped due to clouds: {skipped_cloud_count}")
print(f"Errors: {errors_count}")

SCALE_FACTOR = 5
ITERS = 2000
LR = 2e-3

USE_GNLL = True

DEPTH = 4
HIDDEN_DIM = 256
FOURIER_SCALE = 4
MAPPING_SIZE = 256

INPUT_FOLDER = Path("results/TCI")
OUTPUT_FOLDER = Path("results/SR")
OUTPUT_FOLDER.mkdir(exist_ok=True)

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import numpy
import cv2
from tqdm import tqdm

from pathlib import Path
import glob

# Import the updated INR model and utilities
from models.inr import INR
from models.utils import get_decoder
from input_projections.utils import get_input_projection

def standardize_image(img_tensor):
    """Standardize image to zero mean, unit variance per channel."""
    mean = img_tensor.mean(dim=(0, 1), keepdim=True)
    std = img_tensor.std(dim=(0, 1), keepdim=True)
    std = torch.clamp(std, min=1e-8)
    return (img_tensor - mean) / std, mean, std


def load_lr_images(folder_path):
    """Load all LR images from a folder."""
    extensions = ['*.jpg', '*.JPG', '*.jpeg', '*.JPEG', '*.png', '*.PNG']
    image_paths = []
    for ext in extensions:
        image_paths.extend(glob.glob(str(Path(folder_path) / ext)))

    if not image_paths:
        return None, None, None

    lr_images = []
    means = []
    stds = []

    for img_path in sorted(image_paths):
        img = cv2.imread(str(img_path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        lr_tensor = torch.from_numpy(img).float() / 255.0

        # Standardize
        lr_std, mean, std = standardize_image(lr_tensor)

        lr_images.append(lr_std)
        means.append(mean)
        stds.append(std)

    return lr_images, means, stds


def create_hr_coords(lr_shape, scale_factor):
    """Create HR coordinate grid."""
    lr_h, lr_w = lr_shape[:2]
    hr_h, hr_w = lr_h * scale_factor, lr_w * scale_factor

    hr_coords_h = np.linspace(-1, 1, hr_h, endpoint=False)
    hr_coords_w = np.linspace(-1, 1, hr_w, endpoint=False)
    hr_coords = np.stack(np.meshgrid(hr_coords_w, hr_coords_h, indexing='xy'), -1)

    return torch.FloatTensor(hr_coords)

def train_step(model, optimizer, coords, lr_target, sample_id, scale_factor):
    optimizer.zero_grad()

    if model.use_gnll:
        output, pred_shifts, pred_variance = model(coords, sample_id, scale_factor=scale_factor, training=True, lr_frames=lr_target)
        recon_criterion = nn.GaussianNLLLoss()
        loss = recon_criterion(output, lr_target, pred_variance)
    else:
        output, pred_shifts = model(coords, sample_id, scale_factor=scale_factor, training=True, lr_frames=None)
        loss = F.mse_loss(output, lr_target)

    loss.backward()
    optimizer.step()

    return loss.item()


def evaluate(model, coords, sample_id, mean, std, device):
    with torch.no_grad():
        coords = coords.unsqueeze(0).to(device)
        sample_id = torch.tensor([sample_id]).to(device)
        scale_factor = torch.tensor([1.0]).to(device)  # Not used during inference, but needed for signature

        # Call model - handle different return values based on use_gnll and lr_frames
        model_output = model(coords, sample_id, scale_factor=scale_factor, training=False, lr_frames=None)
        
        # Handle different return signatures
        if model.use_gnll:
            # When use_gnll=True but lr_frames=None, model returns (output, shifts) - 2 values
            # When use_gnll=True and lr_frames is not None, model returns (output, shifts, variances) - 3 values
            if len(model_output) == 3:
                output, _, variance = model_output
                variance = variance.squeeze().cpu().numpy() if variance is not None else None
            else:
                output, _ = model_output
                variance = None
        else:
            # When use_gnll=False, model returns (output, shifts) - 2 values
            output, _ = model_output
            variance = None

        # Unstandardize
        output = output * std.to(device) + mean.to(device)
        output = torch.clamp(output, 0, 1)

        output_np = output.squeeze().cpu().numpy()
        return output_np, variance

import matplotlib.pyplot as plt
import numpy as np
import math

print("Displaying all successfully processed LR images:")
lr_images, means, stds = load_lr_images(INPUT_FOLDER)
num_images = len(lr_images)
cols = 4  # Number of columns in the grid
rows = math.ceil(num_images / cols)

fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 5))
axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

for i, lr_img_tensor in enumerate(lr_images):
    # Unstandardize for visualization
    lr_unstandardized = lr_img_tensor * stds[i] + means[i]
    lr_unstandardized = np.clip(lr_unstandardized, 0, 1)

    ax = axes[i]
    ax.imshow(lr_unstandardized)
    ax.set_title(f"LR Sample {i}")
    ax.axis('off')

# Hide any unused subplots
for j in range(i + 1, len(axes)):
    axes[j].axis('off')

plt.tight_layout()
plt.show()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
lr_images, means, stds = load_lr_images(INPUT_FOLDER)

num_samples = len(lr_images)

lr_shape = lr_images[0].shape
hr_coords = create_hr_coords(lr_shape, SCALE_FACTOR)

scale_factor_tensor = torch.tensor([1.0 / SCALE_FACTOR]).to(device)
hr_coords_batch = hr_coords.unsqueeze(0).to(device)

# Use the updated INR module with proper input projection and decoder
# FourierProjection: when output_dim=MAPPING_SIZE, it outputs MAPPING_SIZE features
# (internally uses MAPPING_SIZE//2 frequencies, outputs sin+cos = MAPPING_SIZE features)
input_projection = get_input_projection(
    input_projection_name="fourier",
    input_dim=2,
    output_dim=MAPPING_SIZE,  # This will output MAPPING_SIZE features
    device=device,
    fourier_scale=FOURIER_SCALE
)

decoder = get_decoder(
    network_name="mlp",
    network_depth=DEPTH,
    input_dim=MAPPING_SIZE,  # Decoder input matches projection output
    network_hidden_dim=HIDDEN_DIM,
    output_dim=3
)

model = INR(
    input_projection=input_projection,
    decoder=decoder,
    num_samples=num_samples,
    use_gnll=USE_GNLL,
    use_base_frame=True,
    use_direct_param_T=True,
    use_color_shift=True
).to(device)

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=0.01)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=ITERS, eta_min=1e-5)

# Create timelapse directory
timelapse_dir = OUTPUT_FOLDER / "timelapse"
timelapse_dir.mkdir(exist_ok=True)

# Timelapse frames list
timelapse_frames = []

pbar = tqdm(total=ITERS, desc="Training")

iteration = 0

while iteration < ITERS:
    for idx in range(num_samples):
        if iteration >= ITERS:
            break

        lr_target = lr_images[idx].unsqueeze(0).to(device)
        sample_id = torch.tensor([idx]).to(device)

        # Train step
        loss = train_step(model, optimizer, hr_coords_batch, lr_target, sample_id, scale_factor_tensor)

        scheduler.step()
        iteration += 1

        # Save intermediate output for timelapse whenever we train on sample 0
        if idx == 0:
            with torch.no_grad():
                # Evaluate on sample 0 for timelapse
                sr_output, _ = evaluate(model, hr_coords, 0, means[0], stds[0], device)
                
                # Save frame
                frame_path = timelapse_dir / f"frame_{iteration:06d}.png"
                sr_uint8 = (np.clip(sr_output, 0, 1) * 255).astype(np.uint8)
                cv2.imwrite(str(frame_path), cv2.cvtColor(sr_uint8, cv2.COLOR_RGB2BGR))
                timelapse_frames.append(frame_path)

        pbar.update(1)
        pbar.set_postfix({'loss': f'{loss:.4f}', 'lr': f'{scheduler.get_last_lr()[0]:.2e}'})

pbar.close()

# Create timelapse video
if timelapse_frames:
    print(f"\nCreating timelapse video from {len(timelapse_frames)} frames...")
    try:
        import imageio.v2 as imageio
        from PIL import Image
        
        # Read all frames
        images = []
        for frame_path in timelapse_frames:
            img = imageio.imread(str(frame_path))
            images.append(img)
        
        # Create video
        timelapse_path = OUTPUT_FOLDER / "timelapse.mp4"
        imageio.mimwrite(str(timelapse_path), images, fps=10, quality=8)
        print(f"✓ Timelapse video saved: {timelapse_path}")
    except ImportError:
        print("Warning: imageio not available. Install with: pip install imageio")
        print(f"Timelapse frames saved in: {timelapse_dir}/")
    except Exception as e:
        print(f"Warning: Could not create timelapse video: {e}")
        print(f"Timelapse frames saved in: {timelapse_dir}/")

# Generate SR outputs
print("\nGenerating SR outputs...")
num_samples = 2
for idx in range(num_samples):
    sr_output, variance = evaluate(model, hr_coords, idx, means[idx], stds[idx], device)

    # Save as PNG
    output_path = OUTPUT_FOLDER / f"sr_sample_{idx:03d}.png"
    sr_uint8 = (np.clip(sr_output, 0, 1) * 255).astype(np.uint8)
    cv2.imwrite(str(output_path), cv2.cvtColor(sr_uint8, cv2.COLOR_RGB2BGR))

    print(f"  Saved: {output_path}")
    
    # Create side-by-side comparison with LR[0] for first output
    if idx == 0:
        # Unstandardize LR sample 0 for visualization
        lr_sample_0 = lr_images[0] * stds[0] + means[0]
        # Convert to numpy array and ensure correct dtype
        if torch.is_tensor(lr_sample_0):
            lr_sample_0_np = lr_sample_0.cpu().numpy()
        else:
            lr_sample_0_np = np.array(lr_sample_0)
        lr_sample_0_np = np.clip(lr_sample_0_np, 0, 1).astype(np.float32)
        
        # Get LR and HR dimensions
        lr_h, lr_w = lr_sample_0_np.shape[:2]
        hr_h, hr_w = sr_output.shape[:2]
        
        # Compute bilinear upsampling (cv2.resize expects float32 in [0, 1] or uint8 in [0, 255])
        lr_bilinear = cv2.resize(lr_sample_0_np, (hr_w, hr_h), interpolation=cv2.INTER_LINEAR)
        lr_bilinear = np.clip(lr_bilinear, 0, 1).astype(np.float32)
        
        # Create comparison figure with 3 images: LR, Bilinear, SR
        fig_comp, axes_comp = plt.subplots(1, 3, figsize=(18, 6))
        axes_comp[0].imshow(lr_sample_0_np)
        axes_comp[0].set_title("LR (Sample 0)", fontsize=14, fontweight='bold')
        axes_comp[0].axis('off')
        
        axes_comp[1].imshow(lr_bilinear)
        axes_comp[1].set_title("Bilinear Upsampling", fontsize=14, fontweight='bold')
        axes_comp[1].axis('off')
        
        axes_comp[2].imshow(sr_output)
        axes_comp[2].set_title("SR Output", fontsize=14, fontweight='bold')
        axes_comp[2].axis('off')
        
        plt.tight_layout()
        
        # Save comparison
        comparison_path = OUTPUT_FOLDER / "lr_vs_sr_comparison.png"
        plt.savefig(comparison_path, bbox_inches='tight', pad_inches=0.1, dpi=300)
        print(f"  Saved comparison: {comparison_path}")
        plt.close(fig_comp)

# Visualize variance maps for each LR sample if using GNLL
if USE_GNLL and model.use_gnll:
    print("\nGenerating variance visualizations for all LR samples...")
    variance_dir = OUTPUT_FOLDER / "variance_visualizations"
    variance_dir.mkdir(exist_ok=True)
    
    # Use all samples for variance visualization
    total_num_samples = len(lr_images)
    for idx in range(total_num_samples):
        # Get SR output and variance for this sample
        sr_output, variance = evaluate(model, hr_coords, idx, means[idx], stds[idx], device)
        
        # Unstandardize LR sample for visualization
        lr_sample = lr_images[idx] * stds[idx] + means[idx]
        if torch.is_tensor(lr_sample):
            lr_sample_np = lr_sample.cpu().numpy()
        else:
            lr_sample_np = np.array(lr_sample)
        lr_sample_np = np.clip(lr_sample_np, 0, 1)
        
        # Get LR dimensions
        lr_h, lr_w = lr_sample_np.shape[:2]
        
        # Resize LR to HR for comparison
        hr_h, hr_w = sr_output.shape[:2]
        lr_resized = cv2.resize(lr_sample_np, (hr_w, hr_h), interpolation=cv2.INTER_LINEAR)
        lr_resized = np.clip(lr_resized, 0, 1).astype(np.float32)
        
        # Process variance - convert to standard deviation for visualization
        if variance is not None:
            # Ensure variance is non-negative
            variance = np.maximum(variance, 0)
            
            # Convert variance to standard deviation (std = sqrt(variance))
            if variance.ndim == 3:
                # Variance is per-channel, convert each channel then take mean
                std_map = np.sqrt(variance).mean(axis=-1)
            else:
                std_map = np.sqrt(variance)
            
            # Normalize std for visualization (use percentile to handle outliers)
            vmin, vmax = np.percentile(std_map, [5, 95])
            
            # Create std visualization
            fig_var, axes_var = plt.subplots(2, 2, figsize=(12, 12))
            
            # Row 1: Images
            axes_var[0, 0].imshow(lr_resized)
            axes_var[0, 0].set_title(f'LR Sample {idx} (upsampled)', fontsize=12, fontweight='bold')
            axes_var[0, 0].axis('off')
            
            axes_var[0, 1].imshow(sr_output)
            axes_var[0, 1].set_title(f'SR Output (Sample {idx})', fontsize=12, fontweight='bold')
            axes_var[0, 1].axis('off')
            
            # Row 2: Standard deviation analysis
            im_var = axes_var[1, 0].imshow(std_map, cmap='viridis', vmin=vmin, vmax=vmax)
            axes_var[1, 0].set_title(f'Standard Deviation Map (Sample {idx})', fontsize=12, fontweight='bold')
            axes_var[1, 0].axis('off')
            plt.colorbar(im_var, ax=axes_var[1, 0], fraction=0.046, pad=0.04, label='Standard Deviation')
            
            # Std overlaid on SR output
            # Normalize std for overlay (0-1 range)
            std_normalized = (std_map - std_map.min()) / (std_map.max() - std_map.min() + 1e-8)
            
            # Create overlay: use std as alpha channel (higher std = more transparent red)
            overlay = np.zeros_like(sr_output)
            overlay[:, :, 0] = std_normalized  # Red channel for std
            
            # Blend overlay with SR output
            alpha = 0.5 * std_normalized[..., np.newaxis]
            blended = sr_output * (1 - alpha) + overlay * alpha
            
            axes_var[1, 1].imshow(blended)
            axes_var[1, 1].set_title(f'SR with Std Overlay (Red=High Std)', fontsize=12, fontweight='bold')
            axes_var[1, 1].axis('off')
            
            plt.tight_layout()
            
            # Save std visualization
            variance_path = variance_dir / f"sample_{idx:03d}_variance_map.png"
            plt.savefig(variance_path, bbox_inches='tight', pad_inches=0.1, dpi=300)
            plt.close(fig_var)
            
            # Save raw std map as numpy array (also save variance for reference)
            np.save(variance_dir / f"sample_{idx:03d}_std.npy", std_map)
            np.save(variance_dir / f"sample_{idx:03d}_variance.npy", variance)
            np.save(variance_dir / f"sample_{idx:03d}_output.npy", sr_output)
            
            print(f"  Saved std visualization: {variance_path}")
            print(f"    Std range: [{std_map.min():.6f}, {std_map.max():.6f}]")
            print(f"    Mean std: {std_map.mean():.6f}")
    
    print(f"\n✓ Standard deviation visualizations saved to: {variance_dir}/")

# Save model
model_path = output_dir / "model.pth"
torch.save({
    'model_state': model.state_dict(),
    'hr_coords': hr_coords,
    'means': means,
    'stds': stds,
}, model_path)
print(f"\nModel saved: {model_path}")

print("\n" + "="*60)
print("OPTIMIZATION COMPLETE!")
print("="*60)



import matplotlib.pyplot as plt

# Display the SR output
plt.figure(figsize=(10, 10))
plt.imshow(sr_output)
plt.title("Super-Resolution Output")
plt.axis('off')
plt.show()



import matplotlib.pyplot as plt
import numpy as np

# Display the LR sample 0 and the SR output side-by-side
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Unstandardize LR sample 0 for visualization
lr_unstandardized = lr_images[1] * stds[1] + means[1]
lr_unstandardized = np.clip(lr_unstandardized, 0, 1) # Clip to [0, 1] range for display

# Display LR sample 0
axes[0].imshow(lr_unstandardized)
#axes[0].set_title("Sentinel-2")
axes[0].axis('off')

# Display SR output
axes[1].imshow(sr_output)
#axes[1].set_title("SuperF: Super-resolution output")
axes[1].axis('off')

plt.tight_layout()
plt.show()
fig.savefig(f"result_{LAT}_{LON}.pdf", format="pdf")
fig.savefig(f"result_{LAT}_{LON}.png")
fig.savefig(f"result_{LAT}_{LON}_transp.png", transparent=True)
